/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import logica_inventario.Controlador_aleatorios;

/**
 *
 * @author j
 */
public class Aleatorios extends javax.swing.JPanel {
    public Aleatorios() {
        initComponents();
        lista_metodos();
    }
    
    public void actualizar_parametros_metodos(){
        
    }
    public void lista_metodos(){
        jComboBox_demanda.removeAllItems();
        jComboBox_demanda.addItem("congruencial mixto");
        jComboBox_demanda.addItem("congruencial multiplicativo");
        jComboBox_demanda.addItem("congruencial cuadratico");
        jComboBox_demanda.addItem("aditivo fibonacci");

        jComboBox_espera.removeAllItems();
        jComboBox_espera.addItem("congruencial mixto");
        jComboBox_espera.addItem("congruencial multiplicativo");
        jComboBox_espera.addItem("congruencial cuadratico");
        jComboBox_espera.addItem("aditivo fibonacci");

        jComboBox_entrega.removeAllItems();
        jComboBox_entrega.addItem("congruencial mixto");
        jComboBox_entrega.addItem("congruencial multiplicativo");
        jComboBox_entrega.addItem("congruencial cuadratico");
        jComboBox_entrega.addItem("aditivo fibonacci");
    }
    public void actualizar_text_area(){
        jTextArea_aleatorios.setText("");
        for(int i=0;i<Ventana_principal.aleatorios_demandas.size();i++){
            jTextArea_aleatorios.setText(jTextArea_aleatorios.getText()+Ventana_principal.aleatorios_demandas.get(i)+"\n");
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_demanda = new javax.swing.JComboBox();
        jButton_generar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_aleatorios = new javax.swing.JTextArea();
        jComboBox_entrega = new javax.swing.JComboBox();
        jComboBox_espera = new javax.swing.JComboBox();

        jComboBox_demanda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_demanda.setBorder(javax.swing.BorderFactory.createTitledBorder("Demanda"));

        jButton_generar.setText("Generar");
        jButton_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_generarActionPerformed(evt);
            }
        });

        jTextArea_aleatorios.setColumns(20);
        jTextArea_aleatorios.setRows(5);
        jTextArea_aleatorios.setBorder(javax.swing.BorderFactory.createTitledBorder("aleatorios_generados"));
        jScrollPane1.setViewportView(jTextArea_aleatorios);

        jComboBox_entrega.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_entrega.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrega"));

        jComboBox_espera.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_espera.setBorder(javax.swing.BorderFactory.createTitledBorder("Espera"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox_demanda, 0, 180, Short.MAX_VALUE)
                        .addComponent(jComboBox_entrega, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jComboBox_espera, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_generar)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox_demanda, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_espera, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_generarActionPerformed
        try{
        if(jComboBox_demanda.getSelectedItem().equals("congruencial mixto")) Ventana_principal.aleatorios_demandas=Controlador_aleatorios.congruensial_mixto(1013,5,3,1);
        if(jComboBox_entrega.getSelectedItem().equals("congruencial mixto")) Ventana_principal.aleatorios_entrega=Controlador_aleatorios.congruensial_mixto(1013,5,3,1);
        if(jComboBox_espera.getSelectedItem().equals("congruencial mixto")) Ventana_principal.aleatorios_espera=Controlador_aleatorios.congruensial_mixto(1013,5,3,1);
        if(jComboBox_demanda.getSelectedItem().equals("congruencial multiplicativo")) Ventana_principal.aleatorios_demandas=Controlador_aleatorios.congruencial_multiplicativo(10000, 211, 17);
        if(jComboBox_entrega.getSelectedItem().equals("congruencial multiplicativo")) Ventana_principal.aleatorios_entrega=Controlador_aleatorios.congruencial_multiplicativo(10000, 211, 17);
        if(jComboBox_espera.getSelectedItem().equals("congruencial multiplicativo")) Ventana_principal.aleatorios_espera=Controlador_aleatorios.congruencial_multiplicativo(10000, 211, 17);
        if(jComboBox_demanda.getSelectedItem().equals("congruencial cuadratico")) Ventana_principal.aleatorios_demandas=Controlador_aleatorios.congruencialCuadratico(2000, 12, 2,53, 15);
        if(jComboBox_entrega.getSelectedItem().equals("congruencial cuadratico")) Ventana_principal.aleatorios_entrega=Controlador_aleatorios.congruencialCuadratico(2000, 12, 2,53, 15);
        if(jComboBox_espera.getSelectedItem().equals("congruencial cuadratico")) Ventana_principal.aleatorios_espera=Controlador_aleatorios.congruencialCuadratico(2000, 12, 2,53, 15);
        if(jComboBox_demanda.getSelectedItem().equals("aditivo fibonacci")) Ventana_principal.aleatorios_demandas=Controlador_aleatorios.metodoAditivoFibonacci(3000,1, 3);
        if(jComboBox_entrega.getSelectedItem().equals("aditivo fibonacci")) Ventana_principal.aleatorios_entrega=Controlador_aleatorios.metodoAditivoFibonacci(3000,1, 3);
        if(jComboBox_espera.getSelectedItem().equals("aditivo fibonacci")) Ventana_principal.aleatorios_espera=Controlador_aleatorios.metodoAditivoFibonacci(3000,1, 3);
        
       
        if(Ventana_principal.aleatorios_demandas.get(0)==-0.1) JOptionPane.showMessageDialog(jButton_generar, "parametros no validos, verifique que siguen las reglas para la generacion");
        else actualizar_text_area();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(jButton_generar, "los valores deben ser solo numericos");
        }
    }//GEN-LAST:event_jButton_generarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_generar;
    private javax.swing.JComboBox jComboBox_demanda;
    private javax.swing.JComboBox jComboBox_entrega;
    private javax.swing.JComboBox jComboBox_espera;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_aleatorios;
    // End of variables declaration//GEN-END:variables
}
