/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author j
 */
public class Tabla extends javax.swing.JPanel {

    /**
     * Creates new form Animacion
     */
    public Tabla() {
        initComponents();
        actualizar_tabla();
    }
    
    public void actualizar_tabla(){
        String[] dato={"punto de orden(Q)","punto de reorden(R)","costo","cantidad de faltantes","cantidad de ventas perdidas"};
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.setColumnIdentifiers(dato);
        for(int i=0;i<Ventana_principal.getInventario().getGastos().size();i++){
            String[] datos=new String[5];
            datos[0]=Ventana_principal.getInventario().getGastos().get(i).getOrden_inicial()+"";
            datos[1]=Ventana_principal.getInventario().getGastos().get(i).getReorden()+"";
            datos[2]=Ventana_principal.getInventario().getGastos().get(i).getGastos()+"";
            datos[3]=Ventana_principal.getInventario().getGastos().get(i).getFaltante()+"";
            datos[4]=Ventana_principal.getInventario().getGastos().get(i).getEntregas_perdidas()+"";
            modelo.addRow(datos);
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
