/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica_proyecto.Inventario;

/**
 *
 * @author j
 */
public class Ventana_principal extends javax.swing.JFrame {
     static Inventario inventario;
     static ArrayList<Double> aleatorios_demandas;
     static ArrayList<Double> aleatorios_espera;
     static ArrayList<Double> aleatorios_entrega;
    /**
     * Creates new form Ventana_principal
     */
    public Ventana_principal() {
        initComponents();
        inventario=new Inventario(260, 1, 1000, 1, 1000);
        aleatorios_demandas=new ArrayList<>();
        jScrollPane_valores.getViewport().add(new Aleatorios());
        jScrollPane_principal.getViewport().add(new Tabla());
        
    }
    public void inventario_grafica_orden(){
        jScrollPane_principal.getViewport().add(new Estadistica(inventario));
    }

    public static ArrayList<Double> getAleatorios_espera() {
        return aleatorios_espera;
    }

    public static void setAleatorios_espera(ArrayList<Double> aleatorios_espera) {
        Ventana_principal.aleatorios_espera = aleatorios_espera;
    }

    public static ArrayList<Double> getAleatorios_entrega() {
        return aleatorios_entrega;
    }

    public static void setAleatorios_entrega(ArrayList<Double> aleatorios_entrega) {
        Ventana_principal.aleatorios_entrega = aleatorios_entrega;
    }
    
    
    public static Inventario getInventario() {
        return inventario;
    }

    public static void setInventario(Inventario inventario) {
        Ventana_principal.inventario = inventario;
    }

    public static ArrayList<Double> getAleatorios() {
        return aleatorios_demandas;
    }

    public static void setAleatorios(ArrayList<Double> aleatorios) {
        Ventana_principal.aleatorios_demandas = aleatorios;
    }
    public  void actualizar_tabla(){
        jScrollPane_principal.getViewport().add(new Tabla());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_principal = new javax.swing.JScrollPane();
        jScrollPane_valores = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_aleatorios = new javax.swing.JMenuItem();
        jMenuItem_inventario = new javax.swing.JMenuItem();
        jMenu_estadisticas = new javax.swing.JMenu();
        jMenuItem_grafica = new javax.swing.JMenuItem();
        jMenuItem_tabla = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Simulacion");

        jMenuItem_aleatorios.setText("Aleatorios");
        jMenuItem_aleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_aleatoriosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_aleatorios);

        jMenuItem_inventario.setText("Inventario");
        jMenuItem_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_inventarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_inventario);

        jMenuBar1.add(jMenu1);

        jMenu_estadisticas.setText("estadisticas");

        jMenuItem_grafica.setText("Grafica");
        jMenuItem_grafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_graficaActionPerformed(evt);
            }
        });
        jMenu_estadisticas.add(jMenuItem_grafica);

        jMenuItem_tabla.setText("Datos obtenidos ");
        jMenuItem_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_tablaActionPerformed(evt);
            }
        });
        jMenu_estadisticas.add(jMenuItem_tabla);

        jMenuBar1.add(jMenu_estadisticas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .addComponent(jScrollPane_valores)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane_valores, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_graficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_graficaActionPerformed
       jScrollPane_principal.getViewport().add(new Estadistica(inventario));
        
    }//GEN-LAST:event_jMenuItem_graficaActionPerformed

    private void jMenuItem_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_inventarioActionPerformed
        if(aleatorios_demandas.size()>0){
            jScrollPane_valores.getViewport().add(new Vista_inventario());
        }
        else JOptionPane.showMessageDialog(rootPane, "debe generar los numeros aleatorios primero antes de empezar con la simulacion");
    }//GEN-LAST:event_jMenuItem_inventarioActionPerformed

    private void jMenuItem_aleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_aleatoriosActionPerformed
        jScrollPane_valores.getViewport().add(new Aleatorios());
    }//GEN-LAST:event_jMenuItem_aleatoriosActionPerformed

    private void jMenuItem_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_tablaActionPerformed
        jScrollPane_principal.getViewport().add(new Tabla());
    }//GEN-LAST:event_jMenuItem_tablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_aleatorios;
    private javax.swing.JMenuItem jMenuItem_grafica;
    private javax.swing.JMenuItem jMenuItem_inventario;
    private javax.swing.JMenuItem jMenuItem_tabla;
    private javax.swing.JMenu jMenu_estadisticas;
    private javax.swing.JScrollPane jScrollPane_principal;
    private javax.swing.JScrollPane jScrollPane_valores;
    // End of variables declaration//GEN-END:variables
}
